// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJMY8xA7zLogdiH0O_5OfhWwMyX2wpm6M',
    appId: '1:978589766146:web:bb845f4a4a455a2dbacd1b',
    messagingSenderId: '978589766146',
    projectId: 'susthiram-92ca8',
    authDomain: 'susthiram-92ca8.firebaseapp.com',
    storageBucket: 'susthiram-92ca8.firebasestorage.app',
    measurementId: 'G-5GML7F6N9H',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI28Z97lDHvfTbJ7SnrQN_iGk2awE7uBI',
    appId: '1:978589766146:ios:d8230b780e5d2c6dbacd1b',
    messagingSenderId: '978589766146',
    projectId: 'susthiram-92ca8',
    storageBucket: 'susthiram-92ca8.firebasestorage.app',
    iosBundleId: 'com.example.susthiram',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI28Z97lDHvfTbJ7SnrQN_iGk2awE7uBI',
    appId: '1:978589766146:ios:d8230b780e5d2c6dbacd1b',
    messagingSenderId: '978589766146',
    projectId: 'susthiram-92ca8',
    storageBucket: 'susthiram-92ca8.firebasestorage.app',
    iosBundleId: 'com.example.susthiram',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNDXC12vJcgcVJGfSnrLpXvU8QDWWTtm8',
    appId: '1:978589766146:android:39b5704075539f69bacd1b',
    messagingSenderId: '978589766146',
    projectId: 'susthiram-92ca8',
    storageBucket: 'susthiram-92ca8.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJMY8xA7zLogdiH0O_5OfhWwMyX2wpm6M',
    appId: '1:978589766146:web:19a63071444074bfbacd1b',
    messagingSenderId: '978589766146',
    projectId: 'susthiram-92ca8',
    authDomain: 'susthiram-92ca8.firebaseapp.com',
    storageBucket: 'susthiram-92ca8.firebasestorage.app',
    measurementId: 'G-VHS18Y5PH5',
  );

}